/* Shadow DOM styles — inlined string so the overlay is fully isolated from YouTube CSS. */
(function () {
  'use strict';
  var CSS = [
    '@font-face {',
    "  font-family: 'YTF Inter';",
    '  font-style: normal;',
    '  font-weight: 100 900;',
    '  font-display: swap;',
    '  src: url("%%YTF_FONT_URL%%") format("woff2");',
    '}',
    ':host { all: initial; }',
    '.ytf-overlay {',
    '  position: fixed; inset: 0; z-index: 2147483647;',
    '  display: flex; align-items: center; justify-content: center;',
    '  padding: 24px; box-sizing: border-box;',
    '  font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "YTF Inter", Inter, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;',
    '  letter-spacing: -0.011em; font-feature-settings: "cv11";',
    '  -webkit-font-smoothing: antialiased;',
    '}',
    '.ytf-overlay[data-theme="light"] { background: rgba(251,251,253,0.72); backdrop-filter: blur(28px) saturate(180%); -webkit-backdrop-filter: blur(28px) saturate(180%); color: #1d1d1f; }',
    '.ytf-overlay[data-theme="dark"] { background: rgba(0,0,0,0.62); backdrop-filter: blur(28px) saturate(180%); -webkit-backdrop-filter: blur(28px) saturate(180%); color: #f5f5f7; }',
    '.ytf-card {',
    '  width: 100%; max-width: 480px; max-height: 90vh; overflow: auto;',
    '  border-radius: 18px; padding: 32px 28px 24px; text-align: center;',
    '  position: relative; box-sizing: border-box;',
    '}',
    '.ytf-overlay[data-theme="light"] .ytf-card { background: rgba(255,255,255,0.86); border: 1px solid rgba(0,0,0,0.08); box-shadow: 0 8px 30px rgba(0,0,0,0.12); }',
    '.ytf-overlay[data-theme="dark"] .ytf-card { background: rgba(28,28,30,0.88); border: 1px solid rgba(255,255,255,0.12); box-shadow: 0 8px 30px rgba(0,0,0,0.5); }',
    '.ytf-card::before { content: ""; position: absolute; inset: 0; border-radius: 18px; pointer-events: none; opacity: 0.035;',
    '  background-image: url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'120\' height=\'120\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\' numOctaves=\'2\'/%3E%3C/filter%3E%3Crect width=\'120\' height=\'120\' filter=\'url(%23n)\'/%3E%3C/svg%3E"); }',
    '.ytf-icon { width: 64px; height: 64px; margin: 0 auto 16px; border-radius: 18px; display: flex; align-items: center; justify-content: center; }',
    '.ytf-overlay[data-theme="light"] .ytf-icon { background: linear-gradient(145deg, #e8e8ed, #f5f5f7); border: 1px solid rgba(0,0,0,0.06); }',
    '.ytf-overlay[data-theme="dark"] .ytf-icon { background: linear-gradient(145deg, #2c2c2e, #1c1c1e); border: 1px solid rgba(255,255,255,0.1); }',
    '.ytf-icon svg { width: 30px; height: 30px; }',
    '.ytf-title { font-size: 22px; line-height: 28px; font-weight: 700; letter-spacing: -0.02em; margin: 0 0 8px; }',
    '.ytf-sub { font-size: 14px; line-height: 20px; margin: 0 0 6px; opacity: 0.9; }',
    '.ytf-btn { appearance: none; border: 0; border-radius: 980px; min-height: 44px; padding: 0 20px;',
    '  font-size: 15px; font-weight: 600; cursor: pointer; font-family: inherit;',
    '  display: inline-flex; align-items: center; justify-content: center; gap: 8px;',
    '  transition: transform 0.08s ease, background 0.15s ease, opacity 0.15s ease; }',
    '.ytf-btn:active { transform: scale(0.98); }',
    '.ytf-btn:disabled { opacity: 0.4; cursor: not-allowed; }',
    '.ytf-btn-primary { background: #0071e3; color: #fff; }',
    '.ytf-btn-primary:hover { background: #0077ed; }',
    '.ytf-btn-secondary { background: rgba(120,120,128,0.18); color: inherit; }',
    '.ytf-study-action { margin-top: 16px; }',
    '.ytf-snooze { margin-top: 16px; padding-top: 14px; border-top: 1px solid rgba(120,120,128,0.3); }',
    '.ytf-snooze p { font-size: 14px; font-weight: 600; margin: 0 0 10px; }',
    '.ytf-pills { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; }',
    '.ytf-pill { border: 1px solid rgba(120,120,128,0.4); background: transparent; color: inherit;',
    '  border-radius: 980px; padding: 8px 14px; font-size: 13px; font-weight: 600; cursor: pointer; font-family: inherit; }',
    '.ytf-pill:hover { border-color: #0071e3; color: #0071e3; }',
    '.ytf-pill:disabled { opacity: 0.35; cursor: not-allowed; }',
    '.ytf-pill:disabled:hover { border-color: rgba(120,120,128,0.4); color: inherit; }',
    '.ytf-choice { position: relative; min-block-size: 44px; overflow: hidden; }',
    '.ytf-choice > span { position: relative; z-index: 1; }',
    '.ytf-choice.ytf-cooling { opacity: 1; }',
    '.ytf-choice.ytf-cooling::after { content: ""; position: absolute; inset: 0; z-index: 0;',
    '  background: rgba(29,29,31,0.48); transform-origin: right center;',
    '  animation: ytf-cooldown-drain var(--ytf-cooldown-ms) linear forwards; }',
    '@keyframes ytf-cooldown-drain { from { transform: scaleX(1); } to { transform: scaleX(0); } }',
    '.ytf-btn:focus-visible, .ytf-pill:focus-visible, .ytf-why summary:focus-visible, .ytf-allow summary:focus-visible { outline: 3px solid #0071e3; outline-offset: 3px; }',
    // Inline layout: same card, but in-flow inside YouTube's own page — no
    // viewport takeover, no backdrop, page stays scrollable and usable.
    '.ytf-overlay.ytf-inline { position: static; inset: auto; z-index: 1;',
    '  background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none;',
    '  padding: 36px 16px; align-items: flex-start; }',
    '.ytf-overlay.ytf-inline .ytf-card { max-width: 560px; }',
    '.ytf-overlay.ytf-inline[data-theme="light"] .ytf-card { background: rgba(255,255,255,0.96); }',
    '.ytf-overlay.ytf-inline[data-theme="dark"] .ytf-card { background: rgba(28,28,30,0.96); }',
    '.ytf-allow { margin-top: 14px; padding-top: 12px; border-top: 1px solid rgba(120,120,128,0.3); }',
    '.ytf-allow summary { cursor: pointer; font-size: 13px; font-weight: 600; }',
    '.ytf-allow .ytf-pills { margin-top: 10px; }',
    '@media (prefers-reduced-motion: reduce) { .ytf-choice.ytf-cooling::after { animation: none; opacity: 0.35; } }',
    '@media (max-width: 520px) { .ytf-card { padding: 24px 18px 18px; } .ytf-title { font-size: 19px; } }'
  ].join('\n');

  window.YTFOCUS = window.YTFOCUS || {};
  window.YTFOCUS.shadowStyles = CSS;
})();
